version: '3.9'

services:
  # PostgreSQL service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: prompt_finder_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  # Rails application service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch

volumes:
  postgres_data:
